disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Python Világ"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2006.01.02"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

  [params.author]
    name = "Dániel Mizsák"
    email = "info@pythonvilag.hu"
    image = "https://avatars.githubusercontent.com/u/62774880"
    imageQuality = 96
    #   headline = "I'm only human"
    #   bio = "A little bit about you"
    links = [
      { youtube = "https://youtube.com/@pythonvilag" },
      { github = "https://github.com/PythonVilag" },
      { linkedin = "https://linkedin.com/in/daniel-mizsak" },
    ]
